/*
 * Copyright 2026 BarcodeMate
 *
 * SPDX-License-Identifier: Apache-2.0
 */

package com.barcodemate.zxing.aztecrune;

import com.barcodemate.zxing.BarcodeFormat;
import com.barcodemate.zxing.BinaryBitmap;
import com.barcodemate.zxing.NotFoundException;
import com.barcodemate.zxing.RGBLuminanceSource;
import com.barcodemate.zxing.Result;
import com.barcodemate.zxing.common.BitMatrix;
import com.barcodemate.zxing.common.HybridBinarizer;
import org.junit.Test;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

/**
 * Aztec Runes generated by bwip-js, an encoder sharing no code with this port
 * or with zxing-cpp. Upstream ships neither unit tests nor sample images for
 * this format, so these are the only verification there is.
 */
public final class AztecRuneReaderTestCase {

  private static final String[] RUNE_0 = {
      "XXX X X X X",
      "XXXXXXXXXXX",
      " X       X ",
      "XX XXXXX XX",
      " X X   X X ",
      "XX X X X XX",
      " X X   X X ",
      "XX XXXXX XX",
      " X       X ",
      " XXXXXXXXXX",
      "  X X X X  ",
  };

  private static final String[] RUNE_42 = {
      "XXX       X",
      "XXXXXXXXXXX",
      "XX       X ",
      " X XXXXX X ",
      "XX X   X X ",
      " X X X X X ",
      "XX X   X XX",
      " X XXXXX XX",
      "XX       XX",
      " XXXXXXXXXX",
      "    X XXX  ",
  };

  private static final String[] RUNE_255 = {
      "XX X X X  X",
      "XXXXXXXXXXX",
      " X       XX",
      "XX XXXXX XX",
      "XX X   X XX",
      " X X X X XX",
      " X X   X X ",
      "XX XXXXX XX",
      "XX       X ",
      " XXXXXXXXXX",
      "  XX  XXX  ",
  };

  @Test
  public void testDecodesGeneratedRunes() throws Exception {
    assertDecodes(RUNE_0, "0");
    assertDecodes(RUNE_42, "42");
    assertDecodes(RUNE_255, "255");
  }

  @Test
  public void testRejectsAnOrdinaryAztecSymbol() {
    // An Aztec symbol's mode message is not inverted, so trying only the
    // inverted reading refuses it rather than reporting a nonsense value.
    // Here the bullseye is present but the ring is empty.
    BitMatrix modules = new BitMatrix(11, 11);
    int c = 5;
    modules.set(c, c);
    for (int d = -2; d <= 2; d++) {
      modules.set(c + d, c - 2);
      modules.set(c + d, c + 2);
      modules.set(c - 2, c + d);
      modules.set(c + 2, c + d);
    }
    try {
      new AztecRuneReader().decode(toBitmap(scale(modules, 6, 24)));
      fail("expected no rune");
    } catch (Exception expected) {
      // as designed
    }
  }

  private static void assertDecodes(String[] rows, String expected) throws Exception {
    for (int moduleSize : new int[] {4, 6, 9}) {
      BitMatrix image = render(rows, moduleSize, 4 * moduleSize);
      Result result = new AztecRuneReader().decode(toBitmap(image));
      assertEquals("module size " + moduleSize, expected, result.getText());
      assertEquals(BarcodeFormat.AZTEC_RUNE, result.getBarcodeFormat());
    }
  }

  private static BinaryBitmap toBitmap(BitMatrix image) {
    int width = image.getWidth();
    int height = image.getHeight();
    int[] pixels = new int[width * height];
    for (int y = 0; y < height; y++) {
      for (int x = 0; x < width; x++) {
        pixels[y * width + x] = image.get(x, y) ? 0xFF000000 : 0xFFFFFFFF;
      }
    }
    return new BinaryBitmap(new HybridBinarizer(new RGBLuminanceSource(width, height, pixels)));
  }

  private static BitMatrix scale(BitMatrix modules, int moduleSize, int quietZone) {
    String[] rows = new String[modules.getHeight()];
    for (int y = 0; y < modules.getHeight(); y++) {
      StringBuilder row = new StringBuilder();
      for (int x = 0; x < modules.getWidth(); x++) {
        row.append(modules.get(x, y) ? 'X' : ' ');
      }
      rows[y] = row.toString();
    }
    return render(rows, moduleSize, quietZone);
  }

  private static BitMatrix render(String[] rows, int moduleSize, int quietZone) {
    int width = rows[0].length() * moduleSize + 2 * quietZone;
    int height = rows.length * moduleSize + 2 * quietZone;
    BitMatrix image = new BitMatrix(width, height);
    for (int y = 0; y < rows.length; y++) {
      for (int x = 0; x < rows[y].length(); x++) {
        if (rows[y].charAt(x) != 'X') {
          continue;
        }
        for (int dy = 0; dy < moduleSize; dy++) {
          for (int dx = 0; dx < moduleSize; dx++) {
            image.set(quietZone + x * moduleSize + dx, quietZone + y * moduleSize + dy);
          }
        }
      }
    }
    return image;
  }
}
